### ISSUE TITLE
UI.Main启动出错

### ISSUE THREAD

**Issue by seamusic** [util-core/Util.Platform.Single#6]
Error: src/app/core/i18n/i18n.service.ts:65:15 - error TS2345: Argument of type 'import("E:/source/net/Util.Platform.Single/src/Util.Platform.Ui.Main/ClientApp/node_modules/@delon/util/config/config.service").AlainConfigService' is not assignable to parameter of type 'import("E:/source/net/Util.Platform.Single/src/Util.Platform.Ui.Main/ClientApp/node_modules/@delon/theme/node_modules/@delon/util/config/config.service").AlainConfigService'.
  Types have separate declarations of a private property 'config'.

环境是 node 18.18.2，windows 11

![image](https://github.com/util-core/Util.Platform.Single/assets/172009/d7b21516-edbd-46e1-b51a-522b32ce56a3)

**Comment by UtilCore** [comment]
Util UI结构已全新调整, 最新体验已接近angular原生开发,目前正在重构中, 请等待更新

**Comment by UtilCore** [comment]
最新代码已更新, readme已添加运行说明
